
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xcrazyfunction.h"

/*
* The configuration table for devices
*/

XCrazyfunction_Config XCrazyfunction_ConfigTable[XPAR_XCRAZYFUNCTION_NUM_INSTANCES] =
{
	{
		XPAR_CRAZYFUNCTION_0_DEVICE_ID,
		XPAR_CRAZYFUNCTION_0_S_AXI_CRTL_BUS_BASEADDR
	}
};


