
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgravity.h"

/*
* The configuration table for devices
*/

XGravity_Config XGravity_ConfigTable[XPAR_XGRAVITY_NUM_INSTANCES] =
{
	{
		XPAR_GRAVITY_0_DEVICE_ID,
		XPAR_GRAVITY_0_S_AXI_CRTLS_BASEADDR
	}
};


