
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xdogain.h"

/*
* The configuration table for devices
*/

XDogain_Config XDogain_ConfigTable[XPAR_XDOGAIN_NUM_INSTANCES] =
{
	{
		XPAR_DOGAIN_0_DEVICE_ID,
		XPAR_DOGAIN_0_S_AXI_CRTL_BUS_BASEADDR
	}
};


